---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: secret-edit
rules:
- apiGroups: [""]
  resources:
  - secrets
  verbs:
  - create
  - get
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: genesis-admin
  namespace: default
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: secret-edit
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: secret-edit
subjects:
- kind: ServiceAccount
  name: genesis-admin
  namespace: default
