Organizations:
- &Org1
  Name: Org1
  ID: Org1MSP
  MSPDir: org1
  Policies:
    Readers:
      Type: Signature
      Rule: "OR('Org1.member')"
    Writers:
      Type: Signature
      Rule: "OR('Org1.member')"
    Admins:
      Type: Signature
      Rule: "OR('Org1.admin')"
  AnchorPeers:
  - Host: peer-0.peer.org1
    Port: 7051
- &Org2
  Name: Org2
  ID: Org2MSP
  MSPDir: org2
  Policies:
    Readers:
      Type: Signature
      Rule: "OR('Org2.member')"
    Writers:
      Type: Signature
      Rule: "OR('Org2.member')"
    Admins:
      Type: Signature
      Rule: "OR('Org2.admin')"
  AnchorPeers:
  - Host: peer-0.peer.org2
    Port: 7051
- &Orderer
  Name: Orderer
  ID: OrdererMSP
  MSPDir: orderer
  Policies:
    Readers:
      Type: Signature
      Rule: "OR('Orderer.member')"
    Writers:
      Type: Signature
      Rule: "OR('Orderer.member')"
    Admins:
      Type: Signature
      Rule: "OR('Orderer.member')"
Orderer: &OrdererDefaults
  OrdererType: solo
  Addresses:
  - orderer-0.orderer.orderer:7050
  BatchTimeout: 2s
  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 99 MB
    PreferredMaxBytes: 512 KB
  Kafka:
  Organizations:
  Policies:
    Readers:
      Type: ImplicitMeta
          Rule: "ANY Readers"
        Writers:
          Type: ImplicitMeta
          Rule: "ANY Writers"
        Admins:
          Type: ImplicitMeta
          Rule: "ALL Admins"
        BlockValidation:
          Type: ImplicitMeta
          Rule: "ANY Writers"
Profiles:
  GenesisProfile:
    Policies:
      Readers:
        Type: ImplicitMeta
        Rule: "ANY Readers"
      Writers:
        Type: ImplicitMeta
        Rule: "ANY Writers"
      Admins:
        Type: ImplicitMeta
        Rule: "ALL Admins"
    Capabilities:
      V1_3: true
    Orderer:
      <<: *OrdererDefaults
      Organizations:
      - *Orderer
      Capabilities:
        V1_1: true
    Consortiums:
      SampleConsortium:
        Organizations:
        - *Org1
        - *Org2
  ChannelProfile:
    Consortium: SampleConsortium
    Policies:
      Readers:
        Type: ImplicitMeta
        Rule: "ANY Readers"
      Writers:
        Type: ImplicitMeta
        Rule: "ANY Writers"
      Admins:
        Type: ImplicitMeta
        Rule: "ALL Admins"
    Capabilities:
      V1_3: true
    Application:
      Policies:
        Readers:
          Type: ImplicitMeta
          Rule: "ANY Readers"
        Writers:
          Type: ImplicitMeta
          Rule: "ANY Writers"
        Admins:
          Type: ImplicitMeta
          Rule: "ALL Admins"
      Capabilities:
        V1_3: true
      Organizations:
      - *Org1
      - *Org2
