---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: org1-admin
  namespace: org1
rules:
- apiGroups: [""]
  resources:
  - secrets
  verbs:
  - create
  - list
  - patch
  - replace
  - delete
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: org1-admin
  namespace: org1
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: org1-admin
  namespace: org1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: org1-admin
subjects:
- kind: ServiceAccount
  name: org1-admin
  namespace: org1
