apiVersion: apps/v1
kind: Deployment
metadata:
  name: peer-org-ca
  namespace: hyperledger
  labels:
    app: hyperledger-fabric
    component: ca
    release: 1.4.1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hyperledger-fabric
      component: ca
  template:
    metadata:
      labels:
        app: hyperledger-fabric
        component: ca
    spec:
      containers:
      - name: ca
        image: hyperledger/fabric-ca:1.4.1
        command: ["sh", "-c"]
        args:
        - fabric-ca-server start -b admin:adminpw