apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: localpvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  selector:
    matchLabels:
      name: localvol