apiVersion: v1
kind: PersistentVolume
metadata:
  name: localvol
  labels:
    type: local
    name: localvol
spec:
  capacity: 
    storage: 2Gi
  accessModes: 
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /tmp/test
    type: DirectoryOrCreate
