apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: peerOrg
  namespace: hyperledger
  labels:
    app: hyperledger-fabric
    component: peer
    release: 1.4.1
spec:
  selector:
    matchLabels:
      app: hyperledger-fabric
      component: peer
      release: 1.4.1
  serviceName: "peer"
  replicas: 2
  template:
    metadata:
      labels:
        app: hyperledger-fabric
        component: peer
        release: 1.4.1
    spec:
      initContainers:
      - name: init-peer
        image: hyperledger/fabric-ca:1.4.1
        command: ['sh', '-c']
        args:
        - if [ ! -d /hyperledger/msp ]; then
            fabric-ca-client enroll -H /hyperledger -u http://${HOSTNAME}:peerpw@ca.org1.com:7054 --csr.names C=KR,ST=Seoul,L=Gangdong-gu,O=org1.com
          fi
        volumeMounts:
        - name: peer-data
          mountPath: /hyperledger
      conatiners:
      - name: peer
        image: hyperledger/fabric-peer:1.4.1
        command: ['sh', '-c']
        args: 
        - export CORE_PEER_ID=${HOSTNAME};
          export CORE_PEER_ADDRESS=${HOSTNAME}:7051;
          export CORE_PEER_GOSSIP_EXTERNALENDPOINT=${HOSTNAME}:7051;
          peer node start
        env:
        - name: CORE_PEER_GOSSIP_USELEADERELECTION
          value: true
        - name: CORE_PEER_GOSSIP_ORGLEADER
          value: false
        - name: CORE_PEER_GOSSIP_BOOTSTRAP
          value: peer-0:7051
        - name: CORE_PEER_LOCALMSPID
          value: Org1MSP
        - name: CORE_PEER_MSPCONFIGPATH
          value: /hyperledger/msp
        - name: CORE_PEER_TLS_ENABLED
          value: false
        ports:
        - name: interface
          containerPort: 7051
        - name: chaincode
          containerPort: 7052
        volumeMounts:
        - name: dockerSock
          mountPath: /host/var/docker.sock
      volumes:
      - name: dockerSock
        hostPath:
          path: /var/run/docker.sock
      volumeMounts:
      - name: peer-data
        mountPath: /hyperledger
  volumeClaimTemplates:
  - metadata:
      name: peer-data
    spec:
      accessMode: ["ReadWriteOnce"]
      storageClassName: local
      resources:
        requests:
          storage: 1Gi