---
apiVersion: batch/v1
kind: Job
metadata:
  name: register-peer
  namespace: org1
spec:
  template:
    spec:
      containers:
      - name: register-peer
        image: hyperledger/fabric-ca:1.4.1
        command: ["sh","-c"]
        args:
        - |
          fabric-ca-client register -M /home/secret/msp -u http://ca.org1:7054 --id.name peer0 --id.type peer --id.maxenrollments 1 --id.secret peerpw
        volumeMounts:
        - name: msp
          mountPath: /home/secret/
      restartPolicy: OnFailure
      volumes:
      - name: msp
        secret:
          secretName: admin
          items:
          - key: IssuerRevocationPublicKey
            path: msp/IssuerRevocationPublicKey
            mode: 0644
          - key: IssuerPublicKey
            path: msp/IssuerPublicKey
            mode: 0644
          - key: cert
            path: msp/signcerts/cert.pem
            mode: 0644
          - key: key
            path: msp/keystore/private.key
            mode: 0600
          - key: CA
            path: msp/cacerts/ca.pem
            mode: 0644
          - key: user
            path: msp/user/empty