---
apiVersion: v1
kind: Secret
metadata:
  name: ca-root
  namespace: {{ template "hlf-org.namespace" . }}
  labels:
    app: ca-root
{{ include "hlf-org.labels" . | indent 4 }}
data:
{{- $root := . }}
{{- with .Values.ca.root }}
  BOOTUSER: {{ .bootstrap.user | b64enc | quote }}
  BOOTPWD: {{ if .bootstrap.pwd }} {{ .bootstrap.pwd | b64enc | quote }} {{ else }} {{ randAlphaNum 32 | b64enc | quote }} {{ end }}
  KEY: {{ $root.Files.Get .privateKey | b64enc | quote }}
  CERT: {{ $root.Files.Get .publicCert | b64enc | quote }}
  {{- if .chainFile }}
  CHAINFILE: {{ $root.Files.Get .chainFile | b64enc | quote }}
  {{- end }}
  {{- if .tls.enabled }}
  TLS_KEY: {{ $root.Files.Get .tls.tlsKey | b64enc | quote }}
  TLS_CERT: {{ $root.Files.Get .tls.tlsCert | b64enc | quote }}
  {{- end }}
{{- end }}